version: '3'

services:
  api:
    container_name: hackaton-xp-backend
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    env_file: .env
    ports:
      - 3001:3001
    volumes:
      - .:/server